FROM ubuntu:22.04

RUN apt update && apt install -y python3 python3-pip uvicorn

WORKDIR /usr/src

COPY code/api_answering.py .
COPY code/requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8000

CMD [ "uvicorn", "api_answering:app", "--host=0.0.0.0" ]